### ISSUE TITLE
(Link) State: Failed, Status: Up

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fabric#150] opened 2021-01-12 14:20 UTC
This is an odd state to be in:

```
Id     | Src                      -> Dst                      | State        | Cost | Latency       | Full Cost    | Status
rdnE   | remote                   -> local                    | Failed       | 1    | 0.1980 0.1983 | 397          | up 
```

**Comment by plorenz** [comment] 2023-10-31 17:40
Hasn't been seen in a long time. Closing as can't reproduce.

**Closed by plorenz** 2023-10-31 17:40 UTC
