### ISSUE TITLE
Link.dropped_msgs reporting on no existent links

### ISSUE THREAD

**Issue by mikegorman-nf** [openziti/fabric#575] opened 2023-01-01 14:43 UTC
The link.dropped_msgs metric is being reported for links (source entity_id's) that do not exist.  Not sure if they used to, or there is some other issue, but it creates a lot of bogus data to be managed.  Over a billion records in a week for a medium sized networks.

**Comment by plorenz** [comment] 2023-01-04 01:54
Duplicate of #567

**Closed by plorenz** 2023-01-04 01:54 UTC
Labels: bug, metrics/reporting, router
